import {
  listConnections,
  saveConnection,
  deleteConnection,
  testConnection,
  getConnection,
  executeQuery,
  getSchema,
  getSchemaSummary,
  getTableDetails,
  tableListRows,
  tableSaveChanges,
  tableTruncate,
  tableFkLookup,
  getDatabaseInfo,
  createTable,
  dropTable,
  renameTable,
  addColumn,
  dropColumn,
  renameColumn,
  alterColumnType,
  setColumnNullable,
  setColumnDefault,
  createIndex,
  dropIndex,
  createSchema,
  listLocalDatabases,
  createLocalDatabase,
  startLocalDatabase,
  stopLocalDatabase,
  deleteLocalDatabase,
} from "./handlers";

export const db = {
  // Connections
  listConnections,
  saveConnection,
  deleteConnection,
  testConnection,
  getConnection,
  // Queries
  executeQuery,
  // Schema
  getSchema,
  getSchemaSummary,
  getTableDetails,
  // Table data
  tableListRows,
  tableSaveChanges,
  tableTruncate,
  tableFkLookup,
  getDatabaseInfo,
  // DDL
  createTable,
  dropTable,
  renameTable,
  addColumn,
  dropColumn,
  renameColumn,
  alterColumnType,
  setColumnNullable,
  setColumnDefault,
  createIndex,
  dropIndex,
  createSchema,
  // Local DB
  listLocalDatabases,
  createLocalDatabase,
  startLocalDatabase,
  stopLocalDatabase,
  deleteLocalDatabase,
};
