import {
  listConnections,
  saveConnection,
  deleteConnection,
  testConnection,
  getConnection,
  executeQuery,
  getSchema,
  getSchemaSummary,
  getTableDetails,
  tableListRows,
  tableSaveChanges,
  tableTruncate,
  tableFkLookup,
  getDatabaseInfo,
  createTable,
  dropTable,
  renameTable,
  addColumn,
  dropColumn,
  renameColumn,
  alterColumnType,
  setColumnNullable,
  setColumnDefault,
  createIndex,
  dropIndex,
  createSchema,
  listLocalDatabases,
  createLocalDatabase,
  startLocalDatabase,
  stopLocalDatabase,
  deleteLocalDatabase,
  findAvailablePort,
  exportSchemaDdl,
  exportTableData,
  executeBatchDdl,
  waitForDatabase,
  importTableRows,
  getEnums,
  getFunctions,
  getSchemaConstraints,
  getSchemaIndexes,
  getTriggers,
  listBranches,
  createBranch,
  deleteBranch,
  switchBranch,
  getBranchInfo,
  previewDeleteBranch,
  mergeBranchSchema,
  renameBranch,
} from "./handlers";

export { driverRegistry, registerDrivers } from "./registry";
export type { DatabaseDriver, DriverConnectionConfig } from "./driver";
export type { DatabaseType } from "./types";

export const db = {
  // Connections
  listConnections,
  saveConnection,
  deleteConnection,
  testConnection,
  getConnection,
  // Queries
  executeQuery,
  // Schema
  getSchema,
  getSchemaSummary,
  getTableDetails,
  // Table data
  tableListRows,
  tableSaveChanges,
  tableTruncate,
  tableFkLookup,
  getDatabaseInfo,
  // DDL
  createTable,
  dropTable,
  renameTable,
  addColumn,
  dropColumn,
  renameColumn,
  alterColumnType,
  setColumnNullable,
  setColumnDefault,
  createIndex,
  dropIndex,
  createSchema,
  // Local DB
  listLocalDatabases,
  createLocalDatabase,
  startLocalDatabase,
  stopLocalDatabase,
  deleteLocalDatabase,
  findAvailablePort,
  // Clone to Local
  exportSchemaDdl,
  exportTableData,
  executeBatchDdl,
  waitForDatabase,
  importTableRows,
  // Schema definitions
  getEnums,
  getFunctions,
  getSchemaConstraints,
  getSchemaIndexes,
  getTriggers,
  // Branches (local DB branching — PostgreSQL only)
  listBranches,
  createBranch,
  deleteBranch,
  switchBranch,
  getBranchInfo,
  previewDeleteBranch,
  mergeBranchSchema,
  renameBranch,
};
