import {
  addColumn,
  alterColumnType,
  createBranch,
  createIndex,
  createLocalDatabase,
  createSchema,
  createTable,
  createTableFromImport,
  deleteBranch,
  deleteConnection,
  deleteLocalDatabase,
  dropColumn,
  dropIndex,
  dropTable,
  executeBatchDdl,
  executeQuery,
  explainQuery,
  exportSchemaDdl,
  exportSchemaIndexes,
  exportTableData,
  findAvailablePort,
  getBranchInfo,
  getConnection,
  getDatabaseInfo,
  getEnums,
  getFunctions,
  getSchema,
  getSchemaConstraints,
  getSchemaIndexes,
  getSchemaSummary,
  getTableDetails,
  getTriggers,
  importDryRun,
  importTableColumns,
  importTableRows,
  listBranches,
  listConnections,
  listLocalDatabases,
  mergeBranchSchema,
  previewDeleteBranch,
  renameBranch,
  renameColumn,
  renameTable,
  saveConnection,
  setColumnDefault,
  setColumnNullable,
  startLocalDatabase,
  stopLocalDatabase,
  switchBranch,
  tableFkLookup,
  tableListRows,
  tableSaveChanges,
  tableTruncate,
  testConnection,
  waitForDatabase,
} from "./handlers";

export type { DatabaseDriver, DriverConnectionConfig } from "./driver";
export { driverRegistry, registerDrivers } from "./registry";
export type { DatabaseType } from "./types";

export const db = {
  addColumn,
  alterColumnType,
  createBranch,
  createIndex,
  createLocalDatabase,
  createSchema,
  // DDL
  createTable,
  createTableFromImport,
  deleteBranch,
  deleteConnection,
  deleteLocalDatabase,
  dropColumn,
  dropIndex,
  dropTable,
  executeBatchDdl,
  executeQuery,
  explainQuery,
  // Clone to Local
  exportSchemaDdl,
  exportSchemaIndexes,
  exportTableData,
  findAvailablePort,
  getBranchInfo,
  getConnection,
  getDatabaseInfo,
  // Schema definitions
  getEnums,
  getFunctions,
  // Schema
  getSchema,
  getSchemaConstraints,
  getSchemaIndexes,
  getSchemaSummary,
  getTableDetails,
  getTriggers,
  importDryRun,
  importTableColumns,
  importTableRows,
  // Branches (local DB branching — PostgreSQL only)
  listBranches,
  // Connections
  listConnections,
  // Local DB
  listLocalDatabases,
  mergeBranchSchema,
  previewDeleteBranch,
  renameBranch,
  renameColumn,
  renameTable,
  saveConnection,
  setColumnDefault,
  setColumnNullable,
  startLocalDatabase,
  stopLocalDatabase,
  switchBranch,
  tableFkLookup,
  // Table data
  tableListRows,
  tableSaveChanges,
  tableTruncate,
  testConnection,
  waitForDatabase,
};
