/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatabaseConnectionIdRouteImport } from './routes/database.$connectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseConnectionIdRoute = DatabaseConnectionIdRouteImport.update({
  id: '/database/$connectionId',
  path: '/database/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database/$connectionId': typeof DatabaseConnectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/database/$connectionId': typeof DatabaseConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/database/$connectionId': typeof DatabaseConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/database/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/database/$connectionId'
  id: '__root__' | '/' | '/database/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabaseConnectionIdRoute: typeof DatabaseConnectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database/$connectionId': {
      id: '/database/$connectionId'
      path: '/database/$connectionId'
      fullPath: '/database/$connectionId'
      preLoaderRoute: typeof DatabaseConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabaseConnectionIdRoute: DatabaseConnectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
