declare module "*.css";

export {};

declare global {
  // This allows TypeScript to pick up the magic constants auto-generated by
  // Forge's Vite plugin with renderer entrypoints for dev/prod.
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;

  interface Window {
    electron?: {
      platform?: string;
      setNativeThemeSource?: (themeSource: "system" | "light" | "dark") => void;
      aiChat?: {
        start: (input: {
          chatId: string;
          connectionId: string;
          dbType: string;
          schemaContext?: string;
          messages: Array<{ role: string; content: string }>;
        }) => void;
        abort: (chatId: string) => void;
        onChunk: (callback: (chunk: AiChatChunk) => void) => () => void;
        onDone: (callback: (result: { chatId: string; finishReason: string; usage?: unknown }) => void) => () => void;
        onError: (callback: (error: { chatId: string; message: string }) => void) => () => void;
      };
    };
  }

  type AiChatChunk =
    | { type: "text"; text: string }
    | { type: "tool-call"; toolName: string; args: unknown }
    | { type: "tool-result"; toolName: string; result: unknown };
}
