declare module '*.css' {
  const content: string;
  export default content;
}

declare module '@fontsource-variable/*';
declare module '@fontsource-variable/geist*';

export {};

declare global {
  // This allows TypeScript to pick up the magic constants auto-generated by
  // Forge's Vite plugin with renderer entrypoints for dev/prod.
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;

  interface Window {
    electron?: {
      platform?: string;
      setNativeThemeSource?: (themeSource: 'system' | 'light' | 'dark') => void;
      aiChat?: {
        start: (input: {
          chatId: string;
          connectionId: string | null;
          mentionedConnectionId?: string | null;
          dbType: string;
          schemaContext?: string;
          connectionInfo?: {
            name: string;
            host: string;
            port: number;
            database: string;
            isLocal?: boolean;
          };
          messages: Array<{ role: string; content: string }>;
        }) => void;
        abort: (chatId: string) => void;
        onChunk: (callback: (chunk: AiChatChunk) => void) => () => void;
        onDone: (callback: (result: { chatId: string; finishReason: string; usage?: unknown }) => void) => () => void;
        onError: (callback: (error: { chatId: string; message: string }) => void) => () => void;
      };
      aiInline?: {
        start: (input: {
          requestId: string;
          dbType: string;
          prompt: string;
          sql?: string;
          schemaContext?: string;
        }) => void;
        abort: (requestId: string) => void;
        onChunk: (callback: (chunk: AiInlineChunk) => void) => () => void;
        onDone: (callback: (result: { requestId: string; finishReason: string; usage?: unknown }) => void) => () => void;
        onError: (callback: (error: { requestId: string; message: string }) => void) => () => void;
      };
    };
  }

  type AiChatChunk =
    | { chatId: string; type: 'text'; text: string }
    | { chatId: string; type: 'tool-call'; toolCallId: string; toolName: string; input: unknown }
    | { chatId: string; type: 'tool-result'; toolCallId: string; toolName: string; result: unknown };

  type AiInlineChunk = { requestId: string; type: 'text'; text: string };
}
